### ISSUE TITLE
multi line

### ISSUE THREAD

**Issue by KottV** [lipido/kargos#13]
Greetings and thank You for great plasmoid.

I wonder, would it be possibe in architecture of concept to implement multiple lines in main item at least?
for example a clock with date below:
9:20
02/08/2017

or for media info:
Band
Songname

**Comment by lipido** [comment]
You can use HTML in your text. Concretely, you can use the [QML supported HTML subset](http://doc.qt.io/qt-5/richtext-html-subset.html).

For example:
``
9:20<br>02/08/2017
 ``

**Comment by KottV** [comment]
Thanks for pointing.
Now I'm trying to align to right, with no success. Should it work?

`echo '<p align="right">long line1<br>line2</p>'`

**Comment by lipido** [comment]
It should, in theory. I don't know if it is possible in an easy way. 😕

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
