### ISSUE TITLE
Request: Dropdown never visible mode

### ISSUE THREAD

**Issue by AndydeCleyre** [lipido/kargos#14]
Panel space is precious, so I would prefer not to take up extra space just for the dropdown button, which is a visual cue but acts the same as any other part of the my applet when clicked.

The current hidden-mode behavior of showing the dropdown icon whenever the dropdown is shown and hiding again when the dropdown is hidden makes the entire panel resize with each click, which is really jarring and unpleasant and affects many other applets.

**Comment by roachsinai** [comment]
Yes, can't agree anymore. Found there is a shadow effect under the panel whenever the dropdown is shown, so I think that's is enough as a reminder. So wish you to remove the visible option, or give a choice to set never visible.

**Comment by roachsinai** [comment]
Have chaged 2 places reverse the `bool` value, but failed to hide button. lol.

https://github.com/lipido/kargos/blob/d5603d1aeb621add425a659344fe772ea9b3b497/plasmoid/contents/ui/ItemTextMouseArea.qml#L38

https://github.com/lipido/kargos/blob/d5603d1aeb621add425a659344fe772ea9b3b497/plasmoid/contents/ui/CompactRepresentation.qml#L163

**Comment by roachsinai** [comment]
https://github.com/lipido/kargos/blob/d5603d1aeb621add425a659344fe772ea9b3b497/plasmoid/contents/ui/CompactRepresentation.qml#L70

change to `visible: false` worked. And you could also add a checkbox at file [ConfigAppearance.qml](https://github.com/lipido/kargos/blob/master/plasmoid/contents/ui/config/ConfigAppearance.qml) to control it.

**Comment by roachsinai** [comment]
Made a pull request, check it! #26
