### ISSUE TITLE
Script colorized output

### ISSUE THREAD

**Issue by silentbugs** [lipido/kargos#15]
Support for the `color=` option, as it doesn't seem to work at the moment.

Example:

`echo "test | size=11 color=#ff0000"` prints `test` with font size 11 in normal color, instead of the given color.

[bitbar's API](https://github.com/matryer/bitbar#plugin-api)

**Comment by lipido** [comment]
I've just made a commit with the feature. Could you try using `kpackagetool5`?

**Comment by silentbugs** [comment]
It seems to be working fine, thanks.
