### ISSUE TITLE
Need a new maintainer?

### ISSUE THREAD

**Issue by shocklateboy92** [lipido/kargos#29]
Hey @lipido,

It looks like this project hasn't had any activity in about 2 years. If your priorities have changed and don't have time for this anymore, please make me a maintainer. I'd like to revive this project (I have a few improvements in mind).

Cheers,
Lasath

**Comment by lipido** [comment]
Hey @shocklateboy92,

Thank you for your interest in collaborating in this project. What kind of improvements do you have in mind?

Cheers,

**Comment by shocklateboy92** [comment]
Hey,

I'll be honest, I kind of just wanted to confirm that this project isn't dead before I started any coding. :smile: 
I'm also willing to take over housekeeping tasks, like triaging bugs and reviewing pull request #26.

I also have some features I want to add, like:
- allowing the use of icons from [Font Awesome](https://fontawesome.com/icons?m=free), using something [like this](https://github.com/benlau/fontawesome.pri). 
- case insensitive attributes (e.g. `imageUrl` instead of `imageURL`).
- allowing use of double quotes instead of just single quotes for attributes

In the super long term, (once I get the hang of this) I kind of want to try and convince plasma developers to let me put this directly into the shell (and make these a new type of applets). That way, users can pick up new kargos scripts by clicking the "Get New Widgets" button.

**Comment by lipido** [comment]
Welcome on board!

**Comment by shocklateboy92** [comment]
Before I close this, I do have one more question:
Would you like me to still submit pull requests for all code changes and wait for you to review? Or should I take over as primary maintainer and advance this project as I see fit?

**Comment by lipido** [comment]
I think that pull requests are the way external developers collaborate with kargos.

In your case, I think that we can do the following:

- Create a "develop" branch where we can push new commits.
- From now, leave the "master" branch for releases (with tag), that will be uploaded to store.kde.org and, thus, accessible for KDE users in plasma (https://store.kde.org/p/1173112/). Indeed, the version in the KDE store is slightly outdated.
- New features should be first submitted to the "Issues" (including us).
- Minor bug fixes, code formatting, can be directly committed and pushed to "develop".
- "Hot fixes" (urgent bug fixes affecting an already released version in KDE store) can be pushed directly to "master".

Versioning policy. x.y.z:
- x: major version, backward incompatible. By now it is 0. It will be 1, when we are fully compliant with OSX bitbar features.
- y: minor version or features version, backward compatible. 
- z: bugfixes.

**Comment by shocklateboy92** [comment]
Actually, there is one thing I would like to do differently than what you just listed.
Can we make it so that `master` is always where PRs and feature branches get merged to?

That way we can have a `release` branch that is more stable and has bug fixes etc. IIRC that's what all the KDE teams to as well on their repos. They actually create branches per major version so they can do servicing, but I think 2 branches are enough for us.

**Comment by lipido** [comment]
Ok. We can have a `release` branch.
