### ISSUE TITLE
Convention for new arguments

### ISSUE THREAD

**Issue by shocklateboy92** [lipido/kargos#32]
I wanted to start the discussion regarding our procedure for adding new arguments (hopefully without minimizing BitBar/Argos compatibility).

This came up when I started thinking about what argument/key to use when implementing #31. My two initial ideas were as follows:
1. Prefix all our extensions with a `kargos`. E.g. `kargos.fa_icon=bug`
2. Keep the same keys, but distinguish based on values,  I.e. `icon=fa:bug`

What do people think? I'll update the readme once we settle on this.

**Comment by lipido** [comment]
I like the first option, i.e. to prefix our "kargos" genuine parameters.

**Comment by shocklateboy92** [comment]
Okay, it's decided then.
