### ISSUE TITLE
Error in latest development version

### ISSUE THREAD

**Issue by lipido** [lipido/kargos#37]
Error loading QML file: file:///home/lipido/git/kargos/plasmoid/contents/ui/main.qml:261:25: Expected token `)'.

**Comment by shocklateboy92** [comment]
What version of Qt/KDE/Plasma are you using?

**Comment by lipido** [comment]
KDE Plasma Version: 5.12.9
KDE Frameworks Version: 5.44.0
Qt Version: 5.9.5
