### ISSUE TITLE
Change button's look

### ISSUE THREAD

**Issue by lipido** [lipido/kargos#6]
@trmdi suggested in #3:

About the buttons effect, can you make it like this:
- The arrow button: exactly like the one of the system tray widget. (no border at all)
- The Run/Go button: remove all the border, set the alpha color (alpha in #rgba) about 90% when the mouse is outside the button, and 100% when the mouse is inside.

**Comment by lipido** [comment]
I have pushed the implementation in 51c1f956a51762ec4da60da7652883b848181ec0: no borders and dropdown icon is the same as the system tray.

However I implemented, but finally removed, the alpha effect in icons. They looked as "aliens" in comparison with the rest of icons in the task bar (for example: system tray icons do not show this effect).

**Comment by trmdi** [comment]
Ok, the buttons look pretty now. 👍 

But I see some new issues in the below picture:
1. Run/Go buttons overlap the title again. And the width is a little long.
2. The icon arrow-down inside the dropdown menu is a little too big?
3. The icon "KDE" on the panel is also too big?
![img](http://i.imgur.com/iy0yPWP.png)

**Comment by lipido** [comment]
I have implemented these ideas. See 317e39d8f11c8f694263149424d42081ee94cc6b

**Comment by trmdi** [comment]
Look better now. 👍 
I think now is the time to create some useful kargos, instead of the boring demos. :)

**Comment by lipido** [comment]
Take a look at the RSS news un examples. It was one of the motivations of kargo. Bring the favulous KNewsTicker back to life!

https://userbase.kde.org/KNewsTicker

It's working on my desktop these days.
