### ISSUE TITLE
A question about `bash` attribute.

### ISSUE THREAD

**Issue by trmdi** [lipido/kargos#7]
How can I pass `kdialog --msgbox Test` to `bash` attribute?
Tried the below `echo` but nothing works:
```bash
echo "This bash doesn't run | bash='kdialog --msgbox Test'"

cmd="kdialog --msgbox Test"
echo "This bash doesn't run too | bash=$cmd"
```

I could create another `.sh` file to place into the `bash` attribute. But could you improve the parser of kargos in this case?

**Comment by lipido** [comment]
Yes, I will fix it shortly. By now you have to place it in an external script.

**Comment by lipido** [comment]
Done in 0800e22ffe01afa3676b82a39a00ee1ecf040adf

Use single quotes, as in your example.

**Comment by trmdi** [comment]
Well done bro. 👍
