### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by alxlg** [lipido/kargos#9]
`$ plasmapkg2 -t plasmoid --install .plasmoid`
produces the following error:
`Error: Installation of  failed: No such file:`

How to compile the .plasmoid file?

Edit: it works with `kpackagetool5 -t Plasma/Applet --install plasmoid`. If it's right please update the README

**Comment by lipido** [comment]
It depends on your plasma version. In older versions, there is `plasmapkg2` (I am using kubuntu 16.04). However, I also have `kpackagetool5`, so I will update the README to only show `kpackagetool5`.
